### PR TITLE
Note explicit support for Python 3.5

### PR DESCRIPTION
**Pull request by felixonmars**
It builds and all tests passed.

### CODE REVIEW

**Comment by txels** [comment]
Thanks for this.
Travis is red, but it's due to newer flake8 versions flagging more issues than before.
I will fix that later.

**Comment by felixonmars** [comment]
I assume you wanted to merge but clicked close instead :P

**Comment by txels** [comment]
Oh dear me, I did.

**Comment by txels** [comment]
Properly merged now :)

**Comment by txels** [comment]
Releasing as 1.0.3

**Comment by felixonmars** [comment]
Thanks :D

**Pull request merged**
