### PR TITLE
Coverage reporting

### PR DESCRIPTION
**Pull request by stevepeak**
I use this ddt in all my projects even Codecov (which I built)

> Thank you for a great tool! I figured I would add report uploading if you are interested. Let me know what you think!

### CODE REVIEW

**Comment by txels** [comment]
Oh Travis CI is failing due to some pep8 version conflict. Not sure where that comes from...

**Comment by txels** [comment]
Hey codecov looks really neat, I'll take a closer look later on!

**Comment by stevepeak** [comment]
Thank! I look forward to your feedback!

**Comment by txels** [comment]
@stevepeak have you figured out the source of the pep8 version conflict? Which of your dependencies is limiting the versions of pep8?

**Comment by stevepeak** [comment]
Not sure what the conflict comes from...

```python
...
install_requires=["requests>=2.0.0", "coverage"] + (["subprocess32"] if sys.version_info[:2] == (2, 6) else []),
...
```
[Extract from `setup.py`](https://github.com/codecov/codecov-python/blob/097f692a0f02649a80de6c98749ca32a126223fc/setup.py#L30)

**Comment by stevepeak** [comment]
@txels the Bash Global Uploader is complete at https://github.com/codecov/codecov-bash it will soon become the featured uploader for Codecov. Thanks!

```yml
sudo: false # (optional) for faster builds
after_success:
  - bash <(curl -s https://codecov.io/bash)
```

**Pull request merged**
