### PR TITLE
Set __wrapped__ for Python 2

### PR DESCRIPTION
**Pull request by nedbat**
This makes ddt work like Python 3's functools.wraps, and also like mock on both Python 2 and Python 3.

I've been working on a nose plugin to clear attributes that might be leaking memory, and this makes it possible.

### CODE REVIEW

**Comment by nedbat** [comment]
FYI @cpennington

**Comment by txels** [comment]
Thanks for this.

**Comment by nedbat** [comment]
Wow, thanks for the speedy merge! Any chance of getting a new release?

**Comment by txels** [comment]
I'll release later after son's bedtime protocol is over ;)

**Comment by txels** [comment]
Just released as 1.1.1

**Comment by nedbat** [comment]
Sweet! thanks so much.

**Pull request merged**
